# The following script is generated by AI (ChatGPT 5.6 Sol, High), but tested by me.
# Not done with a single prompt. It is the result of a dense discussion context and multiple decisions.

from __future__ import annotations

import argparse
import re
import unicodedata
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import pandas as pd
from rdflib import Graph, Literal, Namespace, URIRef
from rdflib.namespace import DCTERMS, RDF, SKOS


BASE_VOCAB_URI = "https://fair.scribis.fr/vocab/"


# ---------------------------------------------------------------------------
# Vocabulary configuration
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class VocabConfig:
    column: str
    scheme: str
    title: str

    # None = field is single-valued.
    # "," = multiple flat concepts.
    # "|" = multiple hierarchical paths.
    multi_separator: str | None = None

    # Only relevant to hierarchical vocabularies such as lex_usage.
    hierarchy_separator: str | None = None


VOCABULARIES: tuple[VocabConfig, ...] = (
    VocabConfig(
        column="lex_nature",
        scheme="nature",
        title="BSS ouvrage nature vocabulary",
    ),
    VocabConfig(
        column="lex_documents",
        scheme="document-type",
        title="BSS document type vocabulary",
        multi_separator=",",
    ),
    VocabConfig(
        column="lex_usage",
        scheme="usage",
        title="BSS usage vocabulary",
        multi_separator="|",
        hierarchy_separator="/",
    ),
    VocabConfig(
        column="lex_fonction",
        scheme="function",
        title="BSS function vocabulary",
        multi_separator="|",
        hierarchy_separator="/",
    ),
    VocabConfig(
        column="lex_recherche",
        scheme="research",
        title="BSS research target vocabulary",
        multi_separator=",",
    ),
    VocabConfig(
        column="lex_reconnaissance",
        scheme="reconnaissance",
        title="BSS reconnaissance objective vocabulary",
        multi_separator=",",
    ),
    VocabConfig(
        column="lex_exploitation",
        scheme="exploitation",
        title="BSS exploited resource vocabulary",
        multi_separator=",",
    ),
    VocabConfig(
        column="lex_utilisation",
        scheme="utilisation",
        title="BSS utilisation vocabulary",
        multi_separator=",",
    ),
    VocabConfig(
        column="lex_etat_physique",
        scheme="physical-state",
        title="BSS physical state vocabulary",
    ),
    VocabConfig(
        column="lex_etat",
        scheme="detailed-state",
        title="BSS detailed state vocabulary",
        multi_separator=",",
    ),
    VocabConfig(
        column="lex_execution",
        scheme="execution-technique",
        title="BSS execution technique vocabulary",
        multi_separator=",",
    ),
    VocabConfig(
        column="lex_organisme",
        scheme="record-organisation",
        title="BSS record organisation vocabulary",
    ),
    VocabConfig(
        column="lex_type_prof_eau_sol",
        scheme="water-depth-observation-type",
        title="BSS water depth observation type vocabulary",
    ),
)


# ---------------------------------------------------------------------------
# Optional human-readable labels
#
# The exact source value is ALWAYS preserved in skos:notation.
# These only improve display labels where we are confident.
# ---------------------------------------------------------------------------

LABEL_OVERRIDES: dict[str, dict[str, str]] = {
    "research": {
        "EAU": "Eau",
        "HYDROCARBURE": "Hydrocarbure",
        "MATERIAUX": "Matériaux",
        "ARGILE": "Argile",
        "SABLE": "Sable",
        "GEOTHERMIE": "Géothermie",
    },
    "nature": {
        "FORAGE": "Forage",
        "PUITS": "Puits",
        "SONDAGE": "Sondage",
        "SOURCE": "Source",
    },
    "physical-state": {
        "OPERATIONNEL": "Opérationnel",
        "REBOUCHE": "Rebouché",
        "NON-REALISE": "Non réalisé",
        "PREVU": "Prévu",
    },
}


# ---------------------------------------------------------------------------
# Cleaning / URI helpers
# ---------------------------------------------------------------------------

def clean_source_value(value: str) -> str:
    """
    Normalize only formatting artefacts.

    Important: we do NOT alter semantic separators such as '-' or '/'.
    """
    value = value.strip()

    # BSS controlled values often end in a legacy trailing period.
    value = value.rstrip(".").strip()

    # Collapse repeated whitespace without changing content otherwise.
    value = re.sub(r"\s+", " ", value)

    return value


def slugify(value: str) -> str:
    """
    Produce deterministic URI-safe path components.

    Example:
        "TRES-BASSE-ENERGIE" -> "tres-basse-energie"
        "GÉOTHERMIE"         -> "geothermie"
    """
    normalized = unicodedata.normalize("NFKD", value)
    ascii_value = normalized.encode("ascii", "ignore").decode("ascii")

    slug = ascii_value.lower()
    slug = re.sub(r"[^a-z0-9]+", "-", slug)
    slug = slug.strip("-")

    if not slug:
        raise ValueError(f"Cannot create URI slug for value: {value!r}")

    return slug


def default_label(code: str) -> str:
    """
    Mechanical display label only.

    The authoritative source representation remains skos:notation.
    """
    return code.replace("-", " ").strip().capitalize()


def label_for(scheme: str, notation: str) -> str:
    override = LABEL_OVERRIDES.get(scheme, {}).get(notation)

    if override:
        return override

    # For hierarchical notation, display only the final segment.
    leaf = notation.split("/")[-1]

    return default_label(leaf)


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------

def split_flat_value(
    raw: str,
    separator: str | None,
) -> list[str]:
    raw = clean_source_value(raw)

    if not raw:
        return []

    if separator is None:
        return [raw]

    values: list[str] = []

    for part in raw.split(separator):
        cleaned = clean_source_value(part)

        if cleaned:
            values.append(cleaned)

    return values


def hierarchy_prefixes(path: str, separator: str = "/") -> list[str]:
    """
    Convert:

        EAU/AGRICULTURE/IRRIGATION

    into:

        EAU
        EAU/AGRICULTURE
        EAU/AGRICULTURE/IRRIGATION
    """
    parts = [
        clean_source_value(part)
        for part in path.split(separator)
        if clean_source_value(part)
    ]

    return [
        separator.join(parts[:index])
        for index in range(1, len(parts) + 1)
    ]


# ---------------------------------------------------------------------------
# Vocabulary extraction
# ---------------------------------------------------------------------------

def extract_notations(
    series: pd.Series,
    config: VocabConfig,
) -> set[str]:
    notations: set[str] = set()

    for value in series.dropna():
        raw = str(value)

        values = split_flat_value(raw, config.multi_separator)

        if config.hierarchy_separator is None:
            notations.update(values)
            continue

        for path in values:
            notations.update(
                hierarchy_prefixes(
                    path,
                    separator=config.hierarchy_separator,
                )
            )

    return notations


# ---------------------------------------------------------------------------
# RDF generation
# ---------------------------------------------------------------------------

def concept_uri(config: VocabConfig, notation: str) -> URIRef:
    scheme_uri = f"{BASE_VOCAB_URI}{config.scheme}"

    if config.hierarchy_separator:
        parts = notation.split(config.hierarchy_separator)
        uri_path = "/".join(slugify(part) for part in parts)
    else:
        uri_path = slugify(notation)

    return URIRef(f"{scheme_uri}/{uri_path}")


def build_vocabulary_graph(
    config: VocabConfig,
    notations: Iterable[str],
) -> Graph:
    graph = Graph()

    graph.bind("skos", SKOS)
    graph.bind("dcterms", DCTERMS)

    scheme_uri = URIRef(f"{BASE_VOCAB_URI}{config.scheme}")

    graph.add((scheme_uri, RDF.type, SKOS.ConceptScheme))
    graph.add(
        (
            scheme_uri,
            DCTERMS.title,
            Literal(config.title, lang="en"),
        )
    )
    graph.add(
        (
            scheme_uri,
            DCTERMS.description,
            Literal(
                (
                    f"Prototype SKOS vocabulary generated from values of "
                    f"{config.column} in the BRGM BSS Loiret export."
                ),
                lang="en",
            ),
        )
    )

    sorted_notations = sorted(set(notations))

    # Detect accidental URI collisions.
    seen_uris: dict[URIRef, str] = {}

    for notation in sorted_notations:
        uri = concept_uri(config, notation)

        previous = seen_uris.get(uri)

        if previous is not None and previous != notation:
            raise ValueError(
                f"URI collision in {config.scheme}: "
                f"{previous!r} and {notation!r} -> {uri}"
            )

        seen_uris[uri] = notation

        graph.add((uri, RDF.type, SKOS.Concept))
        graph.add((uri, SKOS.inScheme, scheme_uri))
        graph.add((uri, SKOS.notation, Literal(notation)))
        graph.add(
            (
                uri,
                SKOS.prefLabel,
                Literal(
                    label_for(config.scheme, notation),
                    lang="fr",
                ),
            )
        )

        # Hierarchical vocabularies: add skos:broader.
        if config.hierarchy_separator:
            parts = notation.split(config.hierarchy_separator)

            if len(parts) == 1:
                graph.add((uri, SKOS.topConceptOf, scheme_uri))
                graph.add((scheme_uri, SKOS.hasTopConcept, uri))

            else:
                parent_notation = config.hierarchy_separator.join(parts[:-1])
                parent_uri = concept_uri(config, parent_notation)

                graph.add((uri, SKOS.broader, parent_uri))

    return graph


# ---------------------------------------------------------------------------
# Main build
# ---------------------------------------------------------------------------

def build_all_vocabularies(
    csv_path: Path,
    output_dir: Path,
) -> None:
    print(f"Reading {csv_path}")

    df = pd.read_csv(
        csv_path,
        sep=";",
        dtype=str,
        low_memory=False,
    )

    output_dir.mkdir(parents=True, exist_ok=True)

    total_concepts = 0

    for config in VOCABULARIES:
        if config.column not in df.columns:
            print(
                f"[WARN] Column {config.column!r} not found. "
                f"Skipping {config.scheme}."
            )
            continue

        notations = extract_notations(
            df[config.column],
            config,
        )

        graph = build_vocabulary_graph(
            config,
            notations,
        )

        output_path = output_dir / f"{config.scheme}.ttl"

        graph.serialize(
            destination=output_path,
            format="turtle",
            encoding="utf-8",
        )

        total_concepts += len(notations)

        print(
            f"[OK] {config.scheme:<30} "
            f"{len(notations):>4} concepts "
            f"-> {output_path}"
        )

    print()
    print(f"Generated {total_concepts} SKOS concepts.")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate BSS SKOS vocabularies from the source CSV."
    )

    project_root = Path(__file__).resolve().parents[1]

    parser.add_argument(
        "--input",
        type=Path,
        default=project_root / "data/raw/bss_export_45.csv",
        help="Path to the BSS CSV export.",
    )

    parser.add_argument(
        "--output",
        type=Path,
        default=project_root / "vocab/generated",
        help="Directory where generated Turtle vocabularies are written.",
    )

    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()

    build_all_vocabularies(
        csv_path=args.input,
        output_dir=args.output,
    )