# The following script is generated by AI (ChatGPT 5.6 Sol, High), but tested by me.
# Not done with a single prompt. It is the result of a dense discussion context and multiple decisions.

from __future__ import annotations

import argparse
import hashlib
import json
import re
import unicodedata

from collections import Counter
from dataclasses import dataclass
from datetime import datetime, timezone
from decimal import Decimal, InvalidOperation
from pathlib import Path
from urllib.parse import quote

import pandas as pd

from rdflib import Graph, Literal, Namespace, URIRef
from rdflib.namespace import DCTERMS, RDF, RDFS, XSD


# ---------------------------------------------------------------------------
# Namespaces
# ---------------------------------------------------------------------------

BASE = "https://fair.scribis.fr"

BSS = Namespace(f"{BASE}/ontology/bss#")

GEO = Namespace("http://www.opengis.net/ont/geosparql#")
SF = Namespace("http://www.opengis.net/ont/sf#")

QUDT = Namespace("http://qudt.org/schema/qudt/")
UNIT = Namespace("http://qudt.org/vocab/unit/")

SOSA = Namespace("http://www.w3.org/ns/sosa/")
TIME = Namespace("http://www.w3.org/2006/time#")

PROV = Namespace("http://www.w3.org/ns/prov#")


# ---------------------------------------------------------------------------
# Vocabulary mapping
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class VocabularyLink:
    column: str
    predicate: URIRef
    scheme: str

    # None = single-valued
    # "," = legacy comma-separated values
    # "|" = multiple hierarchical paths
    separator: str | None = None

    # True for function / usage, where "/" is semantic hierarchy.
    hierarchical: bool = False


VOCAB_LINKS: tuple[VocabularyLink, ...] = (
    VocabularyLink(
        "lex_nature",
        BSS.hasNature,
        "nature",
    ),
    VocabularyLink(
        "lex_documents",
        BSS.hasAvailableDocumentType,
        "document-type",
        separator=",",
    ),
    VocabularyLink(
        "lex_usage",
        BSS.hasUsage,
        "usage",
        separator="|",
        hierarchical=True,
    ),
    VocabularyLink(
        "lex_fonction",
        BSS.hasFunction,
        "function",
        separator="|",
        hierarchical=True,
    ),
    VocabularyLink(
        "lex_recherche",
        BSS.hasResearchTarget,
        "research",
        separator=",",
    ),
    VocabularyLink(
        "lex_reconnaissance",
        BSS.hasReconnaissanceObjective,
        "reconnaissance",
        separator=",",
    ),
    VocabularyLink(
        "lex_exploitation",
        BSS.exploitsResource,
        "exploitation",
        separator=",",
    ),
    VocabularyLink(
        "lex_utilisation",
        BSS.hasUtilisation,
        "utilisation",
        separator=",",
    ),
    VocabularyLink(
        "lex_etat_physique",
        BSS.hasPhysicalState,
        "physical-state",
    ),
    VocabularyLink(
        "lex_etat",
        BSS.hasDetailedState,
        "detailed-state",
        separator=",",
    ),
    VocabularyLink(
        "lex_execution",
        BSS.hasExecutionTechnique,
        "execution-technique",
        separator=",",
    ),
)


BOOLEAN_FIELDS = (
    ("point_eau", BSS.isGroundwaterPoint),
    ("coupe_geologique", BSS.hasGeologicalSection),
    ("log_geol_verifie", BSS.hasVerifiedGeologicalLog),
)


TRUE_VALUES = {
    "1",
    "TRUE",
    "VRAI",
    "OUI",
    "YES",
    "Y",
    "O",

    # BSS presence indicators
    "PRESENT",
    "PRESENTE",
    "PRÉSENT",
    "PRÉSENTE",
}

FALSE_VALUES = {
    "0",
    "FALSE",
    "FAUX",
    "NON",
    "NO",
    "N",

    # BSS absence indicators
    "ABSENT",
    "ABSENTE",
}


# ---------------------------------------------------------------------------
# Diagnostics
# ---------------------------------------------------------------------------

warnings: Counter[str] = Counter()


def warn(message: str) -> None:
    warnings[message] += 1


# ---------------------------------------------------------------------------
# Basic value helpers
# ---------------------------------------------------------------------------

def get_text(row: pd.Series, column: str) -> str | None:
    if column not in row.index:
        return None

    value = row[column]

    if pd.isna(value):
        return None

    text = str(value).strip()

    if not text:
        return None

    return text


def clean_source_value(value: str) -> str:
    """
    Remove formatting artefacts without changing the actual terminology.
    """
    value = value.strip()

    # Legacy vocabulary values frequently end in a period.
    value = value.rstrip(".").strip()

    value = re.sub(r"\s+", " ", value)

    return value


def slugify(value: str) -> str:
    """
    Must remain compatible with build_vocabularies.py.
    """
    normalized = unicodedata.normalize("NFKD", value)

    ascii_value = (
        normalized
        .encode("ascii", "ignore")
        .decode("ascii")
    )

    slug = ascii_value.lower()

    slug = re.sub(r"[^a-z0-9]+", "-", slug)
    slug = slug.strip("-")

    if not slug:
        raise ValueError(
            f"Unable to generate URI slug for value {value!r}"
        )

    return slug


def resource_id(value: str) -> str:
    return quote(value.strip(), safe="")


# ---------------------------------------------------------------------------
# Vocabulary helpers
# ---------------------------------------------------------------------------

def split_vocab_value(
    raw: str,
    separator: str | None,
) -> list[str]:

    raw = clean_source_value(raw)

    if not raw:
        return []

    if separator is None:
        return [raw]

    result: list[str] = []

    for part in raw.split(separator):
        part = clean_source_value(part)

        if part:
            result.append(part)

    return result


def vocabulary_uri(
    scheme: str,
    notation: str,
    hierarchical: bool = False,
) -> URIRef:

    if hierarchical:
        parts = notation.split("/")

        path = "/".join(
            slugify(part)
            for part in parts
        )

    else:
        path = slugify(notation)

    return URIRef(
        f"{BASE}/vocab/{scheme}/{path}"
    )


# ---------------------------------------------------------------------------
# Primitive value parsing
# ---------------------------------------------------------------------------

def parse_decimal(
    raw: str | None,
    field: str,
) -> Decimal | None:

    if raw is None:
        return None

    value = raw.strip().replace("\xa0", "")

    # Allow French decimal representation if encountered.
    if "," in value and "." not in value:
        value = value.replace(",", ".")

    try:
        return Decimal(value)

    except InvalidOperation:
        warn(f"Invalid numeric value in {field}: {raw!r}")
        return None


def parse_boolean(
    raw: str | None,
    field: str,
) -> bool | None:

    if raw is None:
        return None

    value = clean_source_value(raw).upper()

    value = (
        unicodedata.normalize("NFKD", value)
        .encode("ascii", "ignore")
        .decode("ascii")
    )

    if value in TRUE_VALUES:
        return True

    if value in FALSE_VALUES:
        return False

    warn(f"Unknown boolean value in {field}: {raw!r}")

    return None

def parse_date(
    raw: str | None,
    field: str,
) -> str | None:

    if raw is None:
        return None

    raw = raw.strip()

    formats = (
        "%d/%m/%Y",
        "%Y-%m-%d",
        "%d-%m-%Y",
        "%Y/%m/%d",
    )

    for fmt in formats:
        try:
            value = datetime.strptime(raw, fmt).date()

            return value.isoformat()

        except ValueError:
            pass

    warn(f"Invalid date in {field}: {raw!r}")

    return None


# ---------------------------------------------------------------------------
# URI builders
# ---------------------------------------------------------------------------

def work_uri(bss_id: str) -> URIRef:
    return URIRef(
        f"{BASE}/id/ouvrage/{resource_id(bss_id)}"
    )


def record_uri(bss_id: str) -> URIRef:
    return URIRef(
        f"{BASE}/id/record/{resource_id(bss_id)}"
    )


def geometry_uri(bss_id: str) -> URIRef:
    return URIRef(
        f"{BASE}/id/geometry/{resource_id(bss_id)}"
    )


def observation_uri(bss_id: str) -> URIRef:
    return URIRef(
        f"{BASE}/id/observation/"
        f"{resource_id(bss_id)}-water-depth"
    )


def quantity_uri(
    bss_id: str,
    quantity_name: str,
) -> URIRef:

    return URIRef(
        f"{BASE}/id/quantity/"
        f"{resource_id(bss_id)}/{quantity_name}"
    )


def time_uri(
    bss_id: str,
    time_name: str,
) -> URIRef:

    return URIRef(
        f"{BASE}/id/time/"
        f"{resource_id(bss_id)}/{time_name}"
    )


# ---------------------------------------------------------------------------
# RDF helpers
# ---------------------------------------------------------------------------

def add_quantity(
    graph: Graph,
    subject: URIRef,
    predicate: URIRef,
    bss_id: str,
    name: str,
    value: Decimal,
    unit: URIRef,
) -> URIRef:

    quantity = quantity_uri(
        bss_id,
        name,
    )

    graph.add(
        (
            subject,
            predicate,
            quantity,
        )
    )

    graph.add(
        (
            quantity,
            RDF.type,
            QUDT.QuantityValue,
        )
    )

    graph.add(
        (
            quantity,
            QUDT["value"],
            Literal(
                str(value),
                datatype=XSD.decimal,
            ),
        )
    )

    graph.add(
        (
            quantity,
            QUDT["hasUnit"],
            unit,
        )
    )

    return quantity


# ---------------------------------------------------------------------------
# Work conversion
# ---------------------------------------------------------------------------

def add_identity(
    graph: Graph,
    row: pd.Series,
    work: URIRef,
    bss_id: str,
) -> None:

    graph.add(
        (
            work,
            RDF.type,
            BSS.UndergroundWork,
        )
    )

    graph.add(
        (
            work,
            DCTERMS.identifier,
            Literal(bss_id),
        )
    )

    indice = get_text(row, "indice")

    if indice:
        graph.add(
            (
                work,
                BSS.legacyIndex,
                Literal(indice),
            )
        )

    designation = get_text(row, "designation")

    if designation:
        graph.add(
            (
                work,
                BSS.legacyDesignation,
                Literal(designation),
            )
        )

    # Prefer a human-readable source label when available.
    label = (
        get_text(row, "nom_abrege")
        or get_text(row, "libelle")
        or bss_id
    )

    graph.add(
        (
            work,
            RDFS.label,
            Literal(label, lang="fr"),
        )
    )


def add_vocabulary_links(
    graph: Graph,
    row: pd.Series,
    work: URIRef,
) -> None:

    for config in VOCAB_LINKS:

        raw = get_text(
            row,
            config.column,
        )

        if raw is None:
            continue

        values = split_vocab_value(
            raw,
            config.separator,
        )

        for notation in values:

            concept = vocabulary_uri(
                scheme=config.scheme,
                notation=notation,
                hierarchical=config.hierarchical,
            )

            graph.add(
                (
                    work,
                    config.predicate,
                    concept,
                )
            )


def add_boolean_properties(
    graph: Graph,
    row: pd.Series,
    work: URIRef,
) -> None:

    for column, predicate in BOOLEAN_FIELDS:

        value = parse_boolean(
            get_text(row, column),
            column,
        )

        if value is None:
            continue

        graph.add(
            (
                work,
                predicate,
                Literal(
                    value,
                    datatype=XSD.boolean,
                ),
            )
        )


# ---------------------------------------------------------------------------
# Geography
# ---------------------------------------------------------------------------

def add_commune(
    graph: Graph,
    row: pd.Series,
    work: URIRef,
) -> None:

    insee = get_text(
        row,
        "lex_insee_commune",
    )

    if not insee:
        return

    insee = clean_source_value(insee)

    commune = URIRef(
        f"{BASE}/id/commune/{resource_id(insee)}"
    )

    graph.add(
        (
            commune,
            RDF.type,
            BSS.Commune,
        )
    )

    graph.add(
        (
            commune,
            DCTERMS.identifier,
            Literal(insee),
        )
    )

    name = get_text(
        row,
        "lex_nom_commune",
    )

    if name:
        graph.add(
            (
                commune,
                RDFS.label,
                Literal(
                    name.title(),
                    lang="fr",
                ),
            )
        )

    graph.add(
        (
            work,
            BSS.locatedInCommune,
            commune,
        )
    )


def add_geometry(
    graph: Graph,
    row: pd.Series,
    work: URIRef,
    bss_id: str,
) -> None:

    x_raw = get_text(row, "x_ref06")
    y_raw = get_text(row, "y_ref06")

    if not x_raw or not y_raw:
        return

    x = parse_decimal(
        x_raw,
        "x_ref06",
    )

    y = parse_decimal(
        y_raw,
        "y_ref06",
    )

    if x is None or y is None:
        return

    projection = get_text(
        row,
        "lex_projection_ref06",
    )

    # Our exploration established ref06 as Lambert-93.
    # Do not silently assign EPSG:2154 if a contradictory
    # projection appears in the source.
    if projection:
        normalized = (
            unicodedata
            .normalize("NFKD", projection)
            .encode("ascii", "ignore")
            .decode("ascii")
            .upper()
        )

        if (
            "LAMBERT-93" not in normalized
            and "LAMBERT 93" not in normalized
        ):
            warn(
                f"Unexpected ref06 projection: {projection!r}"
            )
            return

    geom = geometry_uri(bss_id)

    graph.add(
        (
            geom,
            RDF.type,
            GEO.Geometry,
        )
    )

    graph.add(
        (
            geom,
            RDF.type,
            SF.Point,
        )
    )

    wkt = (
        "<http://www.opengis.net/def/crs/EPSG/0/2154> "
        f"POINT({x} {y})"
    )

    graph.add(
        (
            geom,
            GEO.asWKT,
            Literal(
                wkt,
                datatype=GEO.wktLiteral,
            ),
        )
    )

    graph.add(
        (
            work,
            GEO.hasGeometry,
            geom,
        )
    )


# ---------------------------------------------------------------------------
# Physical quantities
# ---------------------------------------------------------------------------

def add_physical_quantities(
    graph: Graph,
    row: pd.Series,
    work: URIRef,
    bss_id: str,
) -> None:

    depth = parse_decimal(
        get_text(row, "prof_investigation"),
        "prof_investigation",
    )

    if depth is not None:
        add_quantity(
            graph,
            work,
            BSS.investigationDepth,
            bss_id,
            "investigation-depth",
            depth,
            UNIT.M,
        )

    elevation = parse_decimal(
        get_text(row, "z_sol"),
        "z_sol",
    )

    if elevation is not None:
        add_quantity(
            graph,
            work,
            BSS.groundElevation,
            bss_id,
            "ground-elevation",
            elevation,
            UNIT.M,
        )

    diameter = parse_decimal(
        get_text(row, "diametre_tubage"),
        "diametre_tubage",
    )

    if diameter is not None:
        add_quantity(
            graph,
            work,
            BSS.casingDiameter,
            bss_id,
            "casing-diameter",
            diameter,
            UNIT.MilliM,
        )


# ---------------------------------------------------------------------------
# Groundwater observation
# ---------------------------------------------------------------------------

def add_groundwater_observation(
    graph: Graph,
    row: pd.Series,
    work: URIRef,
    bss_id: str,
) -> None:

    depth_raw = get_text(
        row,
        "prof_eau_sol",
    )

    type_raw = get_text(
        row,
        "lex_type_prof_eau_sol",
    )

    date_raw = get_text(
        row,
        "date_eau_sol",
    )

    # No groundwater observation information.
    if not any(
        (
            depth_raw,
            type_raw,
            date_raw,
        )
    ):
        return

    observation = observation_uri(bss_id)

    graph.add(
        (
            observation,
            RDF.type,
            BSS.GroundwaterDepthObservation,
        )
    )

    graph.add(
        (
            observation,
            SOSA.hasFeatureOfInterest,
            work,
        )
    )

    graph.add(
        (
            observation,
            SOSA.observedProperty,
            BSS.groundwaterDepthBelowGround,
        )
    )

    # Observation type, including cases such as "ouvrage sec".
    if type_raw:

        notation = clean_source_value(
            type_raw
        )

        concept = vocabulary_uri(
            "water-depth-observation-type",
            notation,
        )

        graph.add(
            (
                observation,
                BSS.waterDepthObservationType,
                concept,
            )
        )

    # Phenomenon time.
    date = parse_date(
        date_raw,
        "date_eau_sol",
    )

    if date:

        instant = time_uri(
            bss_id,
            "water-depth",
        )

        graph.add(
            (
                instant,
                RDF.type,
                TIME.Instant,
            )
        )

        graph.add(
            (
                instant,
                TIME.inXSDDate,
                Literal(
                    date,
                    datatype=XSD.date,
                ),
            )
        )

        graph.add(
            (
                observation,
                SOSA.phenomenonTime,
                instant,
            )
        )

    # Numeric result is optional.
    # e.g. "ouvrage sec" may legitimately have no depth.
    depth = parse_decimal(
        depth_raw,
        "prof_eau_sol",
    )

    if depth is not None:

        result = quantity_uri(
            bss_id,
            "groundwater-depth",
        )

        graph.add(
            (
                observation,
                SOSA.hasResult,
                result,
            )
        )

        graph.add(
            (
                result,
                RDF.type,
                QUDT.QuantityValue,
            )
        )

        graph.add(
            (
                result,
                QUDT["value"],
                Literal(
                    str(depth),
                    datatype=XSD.decimal,
                ),
            )
        )

        graph.add(
            (
                result,
                QUDT["hasUnit"],
                UNIT.M,
            )
        )


# ---------------------------------------------------------------------------
# Geological map
# ---------------------------------------------------------------------------

def add_geological_map_sheet(
    graph: Graph,
    row: pd.Series,
    work: URIRef,
) -> None:

    number = get_text(
        row,
        "lex_num_carte_geol",
    )

    name = get_text(
        row,
        "lex_nom_carte_geol",
    )

    if not number:
        return

    number = clean_source_value(number)

    sheet = URIRef(
        f"{BASE}/id/geological-map-sheet/"
        f"{resource_id(number)}"
    )

    graph.add(
        (
            sheet,
            RDF.type,
            BSS.GeologicalMapSheet,
        )
    )

    graph.add(
        (
            sheet,
            DCTERMS.identifier,
            Literal(number),
        )
    )

    if name:
        graph.add(
            (
                sheet,
                RDFS.label,
                Literal(
                    name.title(),
                    lang="fr",
                ),
            )
        )

    graph.add(
        (
            work,
            BSS.associatedGeologicalMapSheet,
            sheet,
        )
    )


# ---------------------------------------------------------------------------
# BSS information record
# ---------------------------------------------------------------------------

def extract_http_url(
    raw: str | None,
) -> str | None:

    if raw is None:
        return None

    # Handles plain URLs as well as spreadsheet hyperlink formulae.
    match = re.search(
        r'https?://[^"\s]+',
        raw,
    )

    if not match:
        return None

    return match.group(0).rstrip(')"')


def add_bss_record(
    graph: Graph,
    row: pd.Series,
    work: URIRef,
    bss_id: str,
) -> None:

    record = record_uri(bss_id)

    graph.add(
        (
            record,
            RDF.type,
            BSS.BSSRecord,
        )
    )

    graph.add(
        (
            record,
            DCTERMS.identifier,
            Literal(bss_id),
        )
    )

    graph.add(
        (
            record,
            BSS.describesWork,
            work,
        )
    )

    entry_date = parse_date(
        get_text(row, "date_saisie"),
        "date_saisie",
    )

    if entry_date:
        graph.add(
            (
                record,
                BSS.recordEntryDate,
                Literal(
                    entry_date,
                    datatype=XSD.date,
                ),
            )
        )

    modified = parse_date(
        get_text(row, "date_dern_maj"),
        "date_dern_maj",
    )

    if modified:
        graph.add(
            (
                record,
                DCTERMS.modified,
                Literal(
                    modified,
                    datatype=XSD.date,
                ),
            )
        )

    organisation = get_text(
        row,
        "lex_organisme",
    )

    if organisation:

        concept = vocabulary_uri(
            "record-organisation",
            clean_source_value(
                organisation
            ),
        )

        graph.add(
            (
                record,
                BSS.recordOrganisation,
                concept,
            )
        )

    info_url = extract_http_url(
        get_text(row, "lien_infoterre")
    )

    if info_url:
        graph.add(
            (
                record,
                RDFS.seeAlso,
                URIRef(info_url),
            )
        )


# ---------------------------------------------------------------------------
# Dataset-level provenance
# ---------------------------------------------------------------------------

def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()

    with path.open("rb") as file:
        while chunk := file.read(1024 * 1024):
            digest.update(chunk)

    return digest.hexdigest()


def add_provenance_start(
    graph: Graph,
    csv_path: Path,
    started_at: datetime,
) -> tuple[URIRef, URIRef, URIRef]:

    source = URIRef(
        f"{BASE}/id/dataset/bss-loiret-source"
    )

    activity = URIRef(
        f"{BASE}/id/activity/bss-rdf-conversion"
    )

    result = URIRef(
        f"{BASE}/id/dataset/bss-loiret-rdf"
    )

    graph.add(
        (
            source,
            RDF.type,
            PROV.Entity,
        )
    )

    graph.add(
        (
            source,
            DCTERMS.title,
            Literal(
                "BRGM BSS Loiret CSV export",
                lang="en",
            ),
        )
    )

    graph.add(
        (
            source,
            DCTERMS.identifier,
            Literal(
                f"sha256:{sha256_file(csv_path)}"
            ),
        )
    )

    graph.add(
        (
            activity,
            RDF.type,
            PROV.Activity,
        )
    )

    graph.add(
        (
            activity,
            PROV.used,
            source,
        )
    )

    graph.add(
        (
            activity,
            PROV.startedAtTime,
            Literal(
                started_at.isoformat(),
                datatype=XSD.dateTime,
            ),
        )
    )

    graph.add(
        (
            result,
            RDF.type,
            PROV.Entity,
        )
    )

    graph.add(
        (
            result,
            DCTERMS.title,
            Literal(
                "BSS Loiret semantic RDF dataset",
                lang="en",
            ),
        )
    )

    graph.add(
        (
            result,
            PROV.wasDerivedFrom,
            source,
        )
    )

    graph.add(
        (
            result,
            PROV.wasGeneratedBy,
            activity,
        )
    )

    return source, activity, result


# ---------------------------------------------------------------------------
# Complete row conversion
# ---------------------------------------------------------------------------

def convert_row(
    graph: Graph,
    row: pd.Series,
) -> bool:

    bss_id = get_text(
        row,
        "ID_BSS",
    )

    if not bss_id:
        warn("Row without ID_BSS")
        return False

    bss_id = clean_source_value(
        bss_id
    )

    work = work_uri(bss_id)

    add_identity(
        graph,
        row,
        work,
        bss_id,
    )

    add_vocabulary_links(
        graph,
        row,
        work,
    )

    add_boolean_properties(
        graph,
        row,
        work,
    )

    add_commune(
        graph,
        row,
        work,
    )

    add_geometry(
        graph,
        row,
        work,
        bss_id,
    )

    add_physical_quantities(
        graph,
        row,
        work,
        bss_id,
    )

    add_groundwater_observation(
        graph,
        row,
        work,
        bss_id,
    )

    add_geological_map_sheet(
        graph,
        row,
        work,
    )

    add_bss_record(
        graph,
        row,
        work,
        bss_id,
    )

    return True


# ---------------------------------------------------------------------------
# Main conversion
# ---------------------------------------------------------------------------

def build_graph(
    csv_path: Path,
    limit: int | None = None,
) -> tuple[Graph, dict]:

    print(f"Reading {csv_path}")

    df = pd.read_csv(
        csv_path,
        sep=";",
        dtype=str,
        low_memory=False,
    )

    if "ID_BSS" not in df.columns:
        raise ValueError(
            "Required column ID_BSS not found."
        )

    if limit is not None:
        df = df.head(limit)

    graph = Graph()

    graph.bind("bsspoc", BSS)
    graph.bind("geo", GEO)
    graph.bind("sf", SF)
    graph.bind("qudt", QUDT)
    graph.bind("unit", UNIT)
    graph.bind("sosa", SOSA)
    graph.bind("time", TIME)
    graph.bind("prov", PROV)
    graph.bind("dcterms", DCTERMS)

    started_at = datetime.now(
        timezone.utc
    )

    _, activity, result = add_provenance_start(
        graph,
        csv_path,
        started_at,
    )

    converted = 0

    total = len(df)

    for index, (_, row) in enumerate(
        df.iterrows(),
        start=1,
    ):

        if convert_row(
            graph,
            row,
        ):
            converted += 1

        if index % 5000 == 0:
            print(
                f"Processed {index:,}/{total:,} rows..."
            )

    ended_at = datetime.now(
        timezone.utc
    )

    graph.add(
        (
            activity,
            PROV.endedAtTime,
            Literal(
                ended_at.isoformat(),
                datatype=XSD.dateTime,
            ),
        )
    )

    graph.add(
        (
            result,
            PROV.generatedAtTime,
            Literal(
                ended_at.isoformat(),
                datatype=XSD.dateTime,
            ),
        )
    )

    report = {
        "input_rows": total,
        "converted_rows": converted,
        "triples": len(graph),
        "started_at": started_at.isoformat(),
        "ended_at": ended_at.isoformat(),
        "warnings": dict(
            warnings.most_common()
        ),
    }

    return graph, report


def parse_args() -> argparse.Namespace:

    project_root = (
        Path(__file__)
        .resolve()
        .parents[1]
    )

    parser = argparse.ArgumentParser(
        description=(
            "Convert the BRGM BSS Loiret CSV export "
            "to semantic RDF."
        )
    )

    parser.add_argument(
        "--input",
        type=Path,
        default=(
            project_root
            / "data/raw/bss_export_45.csv"
        ),
    )

    parser.add_argument(
        "--output",
        type=Path,
        default=(
            project_root
            / "data/processed/bss-loiret.nt"
        ),
    )

    parser.add_argument(
        "--report",
        type=Path,
        default=(
            project_root
            / "data/processed/conversion-report.json"
        ),
    )

    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help=(
            "Convert only the first N rows. "
            "Useful for testing."
        ),
    )

    return parser.parse_args()


def main() -> None:

    args = parse_args()

    args.output.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    graph, report = build_graph(
        csv_path=args.input,
        limit=args.limit,
    )

    print()
    print(
        f"Serializing {len(graph):,} triples..."
    )

    graph.serialize(
        destination=args.output,
        format="nt",
        encoding="utf-8",
    )

    args.report.write_text(
        json.dumps(
            report,
            indent=2,
            ensure_ascii=False,
        ),
        encoding="utf-8",
    )

    print()
    print(
        f"[OK] RDF:    {args.output}"
    )
    print(
        f"[OK] Report: {args.report}"
    )
    print(
        f"[OK] Rows:   {report['converted_rows']:,}"
    )
    print(
        f"[OK] Triples:{report['triples']:,}"
    )

    if warnings:
        print()
        print("Warnings:")

        for message, count in warnings.most_common(20):
            print(
                f"  {count:>6} × {message}"
            )


if __name__ == "__main__":
    main()